#
# Backup current running-config.
# This config file will be used to verify that there were no manually changes made on the device.
#
---
- name: backup current running config
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/system_vars/vars.yml"

  vars:
    device_backup_dir: "{{backup_dir}}/{{inventory_hostname}}"
    provider:
      host: "{{oob_ip}}"
      username: "{{adminUID}}"
      password: "{{adminPW}}"
      transport: cli

  tasks:
  - name: include service_vars per device
    include_vars: "{{ item }}"
    with_first_found:
      - "{{inventory_dir}}/service_vars/{{inventory_hostname}}.yml"
      - "{{inventory_dir}}/service_vars/default.yml"
  - name: "include task: backup running config"
    include: "{{ inventory_dir }}/common/backup_run_conf.yml" 
    vars:
      file_name: "{{device_backup_dir}}/{{inventory_hostname}}_current_run.conf"
